<script setup lang="ts">
import {ref,computed,onMounted} from 'vue'
import {CalendarDays,ChevronLeft,ChevronRight,Search,ArrowUpRight,Download,Upload,History,Layers,MessageCircle,Clock,Plus,X,Check,SlidersHorizontal,EyeOff,ArrowLeft,LoaderCircle,Sparkles,ExternalLink} from 'lucide-vue-next'
import ArchivePanel from './ArchivePanel.vue'
import type {Activity,ImportResult,RecordData} from './types'

const base=import.meta.env.BASE_URL
const activities=ref<Activity[]>([]),imports=ref<ImportResult[]>([])
const loading=ref(true),error=ref(''),notice=ref(''),busy=ref(false),demo=ref(false)
const view=ref<'calendar'|'records'|'imports'|'archives'>('calendar'),q=ref(''),source=ref(''),tag=ref(''),showHidden=ref(false)
const today=ref(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai'}).format(new Date()))
const month=ref(today.value.slice(0,7)),selected=ref(today.value)
const editing=ref<Activity|null>(null),editTitle=ref(''),editSummary=ref(''),editTags=ref(''),editHidden=ref(false)
const archiveConversation=ref<{source:string;id:string}|null>(null)
const importOpen=ref(false),importBody=ref<any>(null),preview=ref<ImportResult|null>(null),fileName=ref('')
let noticeTimer:ReturnType<typeof setTimeout>|undefined
function toast(s:string){notice.value=s;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>notice.value='',4500)}
async function api(path:string,options:RequestInit={}){const r=await fetch(base+'api/v1/'+path,{...options,headers:{'Content-Type':'application/json',...options.headers}});if(r.status===401){throw Error('设备登录已失效，请从服务器门户重新登录。')}const data=await r.json();if(!r.ok){const reasons=data.items?.filter((x:any)=>x.reason).map((x:any)=>x.reason).slice(0,3).join('；');throw Error(data.error||reasons||'请求失败，请稍后重试')}return data}
async function load(){loading.value=true;error.value='';try{const [info,batches]=await Promise.all([api('info'),api('imports')]);demo.value=info.demo;today.value=info.today;imports.value=batches.items;const all:Activity[]=[];let offset=0;while(true){const page=await api(`activities?include_hidden=true&limit=1000&offset=${offset}`);all.push(...page.items);offset+=page.items.length;if(offset>=page.total||page.items.length===0)break}activities.value=all}catch(e){error.value=(e as Error).message}finally{loading.value=false}}
function title(a:Activity){return a.annotation.title??a.record.title}
function summary(a:Activity){return a.annotation.summary??a.record.summary}
function tags(a:Activity){return [...new Set([...(a.record.source_label?[a.record.source_label]:[]),...(a.annotation.tags??a.record.tags)])]}
const sourceLabels=computed(()=>new Map(activities.value.filter(a=>a.record.source_label).map(a=>[a.record.source,a.record.source_label])))
const sources=computed(()=>[...new Set([...activities.value.map(x=>x.record.source),...imports.value.flatMap(x=>(x.coverage||[]).map(c=>c.source))])].sort())
const allTags=computed(()=>[...new Set(activities.value.flatMap(tags))].sort())
const filtered=computed(()=>activities.value.filter(a=>(showHidden.value||!a.annotation.hidden)&&(!source.value||a.record.source===source.value)&&(!tag.value||tags(a).includes(tag.value))&&(!q.value||(title(a)+' '+summary(a)+' '+tags(a).join(' ')).toLowerCase().includes(q.value.toLowerCase()))))
const monthly=computed(()=>filtered.value.filter(a=>a.record.activity_date.startsWith(month.value)))
const byDay=computed(()=>{const m=new Map<string,Activity[]>();for(const a of monthly.value){const d=a.record.activity_date;m.set(d,[...(m.get(d)||[]),a])}return m})
const dayItems=computed(()=>[...(byDay.value.get(selected.value)||[])].sort((a,b)=>(a.record.first_activity_at||'z').localeCompare(b.record.first_activity_at||'z')))
const recordList=computed(()=>[...monthly.value].sort((a,b)=>b.record.activity_date.localeCompare(a.record.activity_date)||(b.record.first_activity_at||'').localeCompare(a.record.first_activity_at||'')))
const cells=computed(()=>{const [y,m]=month.value.split('-').map(Number);const first=new Date(y,m-1,1);const pad=(first.getDay()+6)%7;const length=new Date(y,m,0).getDate();return Array.from({length:Math.ceil((pad+length)/7)*7},(_,i)=>{const n=i-pad+1;return n<1||n>length?null:month.value+'-'+String(n).padStart(2,'0')})})
const monthLabel=computed(()=>{const [y,m]=month.value.split('-');return `${y} 年 ${Number(m)} 月`})
const dayLabel=computed(()=>{const d=new Date(selected.value+'T12:00:00');return `${d.getMonth()+1} 月 ${d.getDate()} 日`})
const weekday=computed(()=>new Intl.DateTimeFormat('zh-CN',{weekday:'long'}).format(new Date(selected.value+'T12:00:00')))
const stats=computed(()=>{const known=monthly.value.filter(a=>a.record.user_message_count!==null);return{messages:known.reduce((n,a)=>n+(a.record.user_message_count||0),0),unknown:monthly.value.length-known.length,estimated:known.some(a=>a.record.quality.count!=='observed'),days:new Set(monthly.value.filter(a=>a.record.user_message_count===null||(a.record.user_message_count||0)>0).map(a=>a.record.activity_date)).size,conversations:new Set(monthly.value.filter(a=>a.record.conversation_id).map(a=>a.record.source+'\0'+a.record.conversation_id)).size,unidentified:monthly.value.some(a=>!a.record.conversation_id),topics:monthly.value.length}})
const lastImport=computed(()=>imports.value[0]?.created_at)
const coverages=computed(()=>imports.value.flatMap(i=>i.coverage||[]))
function coverage(date:string){return coverages.value.filter(c=>c.from<=date&&c.to>=date&&(!source.value||c.source===source.value))}
function dayCount(date:string){const rows=byDay.value.get(date)||[];return rows.every(a=>a.record.user_message_count===null)?'?':rows.reduce((s,a)=>s+(a.record.user_message_count||0),0)}
function moveMonth(n:number){const [y,m]=month.value.split('-').map(Number);const d=new Date(y,m-1+n,1);month.value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;selected.value=month.value===today.value.slice(0,7)?today.value:month.value+'-01'}
function goToday(){month.value=today.value.slice(0,7);selected.value=today.value}
function timeLabel(s:string|null,timezone='Asia/Shanghai'){return s?new Intl.DateTimeFormat('zh-CN',{timeZone:timezone,hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(s)):'时间未记录'}
function countLabel(r:RecordData){return r.user_message_count===null?'次数未知':`${r.quality.count==='estimated'?'约 ':''}${r.user_message_count} 次交流`}
function dateTime(s?:string){return s?new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(s)):'尚未导入'}
function duration(rows:Activity[]){const intervals=rows.flatMap(a=>a.record.spans.map(s=>[Date.parse(s.start),Date.parse(s.end)] as [number,number])).sort((a,b)=>a[0]-b[0]);if(!intervals.length)return null;let total=0,[a,b]=intervals[0];for(const [c,d]of intervals.slice(1)){if(c<=b)b=Math.max(b,d);else{total+=b-a;a=c;b=d}}return Math.round((total+b-a)/60000)}
function openEdit(a:Activity){editing.value=a;editTitle.value=title(a);editSummary.value=summary(a);editTags.value=(a.annotation.tags??a.record.tags).join('，');editHidden.value=a.annotation.hidden||false}
async function saveEdit(reset=false){if(!editing.value)return;busy.value=true;error.value='';try{const a=editing.value;await api(`activities/${a.id}/annotation`,{method:'PATCH',body:JSON.stringify({expected_version:a.annotation_version,annotation:reset?{hidden:false}:{title:editTitle.value,summary:editSummary.value,tags:editTags.value.split(/[,，]/).map(x=>x.trim()).filter(Boolean),hidden:editHidden.value}})});editing.value=null;await load();toast(reset?'已恢复来源内容':'修改已保存，重新导入也会保留')}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function selectFile(event:Event){const file=(event.target as HTMLInputElement).files?.[0];preview.value=null;importBody.value=null;if(!file)return;fileName.value=file.name;try{if(file.size>1048576)throw Error('单批文件最多 1 MiB，请用 skill 分批导入');importBody.value=JSON.parse(await file.text());error.value=''}catch(e){error.value=(e as Error).message}}
async function doImport(commit=false){if(!importBody.value)return;busy.value=true;error.value='';try{const result=await api(commit?'imports':'imports/preview',{method:'POST',body:JSON.stringify(importBody.value)});preview.value=result;if(commit){importOpen.value=false;await load();toast(result.replay?'这批记录已经导入，无需重复写入':`已导入：新增 ${result.inserted} 条，更新 ${result.updated} 条`)}}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
function newImport(){importOpen.value=true;importBody.value=null;preview.value=null;fileName.value='';error.value=''}
function closeDialogs(e:KeyboardEvent){if(e.key==='Escape'&&!busy.value){if(archiveConversation.value)archiveConversation.value=null;else{editing.value=null;importOpen.value=false}}}
onMounted(()=>{load();document.addEventListener('keydown',closeDialogs)})
</script>

<template>
 <div class="app-shell">
  <aside class="sidebar">
   <a class="brand" :href="base"><span class="brand-mark"><CalendarDays :size="23"/></span><span>AICalendar<small>AI 活动日历</small></span></a>
   <div class="nav-label">我的活动</div>
   <nav>
    <button :class="{active:view==='calendar'}" @click="view='calendar'"><CalendarDays :size="18"/><span>日历</span></button>
    <button :class="{active:view==='records'}" @click="view='records'"><Layers :size="18"/><span>所有记录</span></button>
    <button :class="{active:view==='archives'}" @click="view='archives'"><MessageCircle :size="18"/><span>聊天存档</span></button>
    <button :class="{active:view==='imports'}" @click="view='imports'"><History :size="18"/><span>导入历史</span></button>
   </nav>
   <div class="sidebar-bottom"><div class="quiet-note"><span class="status-dot"></span>按你的节奏，整理与回顾<p>最近整理<br><strong>{{dateTime(lastImport)}}</strong></p></div><a class="portal-link" href="/portal/">服务器门户<ArrowUpRight :size="15"/></a></div>
  </aside>
  <main>
   <header class="page-header"><div><div class="eyebrow">YOUR AI JOURNEY</div><h1>{{view==='calendar'?'留住每一次探索':view==='records'?'那些聊过的事':view==='archives'?'保留每一段对话':'记录从这里汇集'}}</h1><p>{{view==='imports'?'每次整理的来源、范围与结果。':'回顾与 AI 一起思考、创造和解决问题的日子。'}}</p></div><button class="primary" @click="newImport"><Plus :size="17"/>导入记录</button></header>
   <div v-if="demo" class="demo-label">本地演示环境 · 使用合成数据</div>
   <div v-if="error" class="error-banner" role="alert">{{error}}<button @click="error=''" aria-label="关闭错误"><X :size="17"/></button></div>
   <div v-if="notice" class="toast" role="status"><Check :size="17"/>{{notice}}</div>
   <div v-if="loading" class="loading"><LoaderCircle class="spin" :size="22"/>正在整理页面…</div>
   <template v-else-if="view!=='imports'&&view!=='archives'">
    <section class="stats">
     <div class="stat"><span>本月交流<MessageCircle :size="16"/></span><strong>{{stats.estimated?'约 ':''}}{{stats.unknown===monthly.length&&stats.unknown>0?'—':stats.messages}}<small>次</small></strong><p>{{stats.unknown?`另有 ${stats.unknown} 条记录的次数未知`:'按用户发送次数统计'}}</p></div>
     <div class="stat"><span>交流过的会话<Layers :size="16"/></span><strong>{{stats.conversations}}<small>个</small></strong><p>{{stats.unidentified?'部分记录没有会话标识':'同一会话跨天只计一次'}}</p></div>
     <div class="stat"><span>活跃日<CalendarDays :size="16"/></span><strong>{{stats.days}}<small>天</small></strong><p>基于已导入的记录</p></div>
     <div class="stat"><span>每日主题<Sparkles :size="16"/></span><strong>{{stats.topics}}<small>条</small></strong><p>记录想法，也记录进展</p></div>
    </section>
    <section class="workspace">
     <div class="toolbar"><div class="month-picker"><h2>{{monthLabel}}</h2><div class="month-buttons"><button @click="moveMonth(-1)" aria-label="上个月"><ChevronLeft :size="18"/></button><button @click="goToday" class="today-button">今天</button><button @click="moveMonth(1)" aria-label="下个月"><ChevronRight :size="18"/></button></div></div><div class="search"><Search :size="17"/><input v-model="q" placeholder="搜索主题、摘要…" aria-label="搜索记录"/><button v-if="q" @click="q=''" aria-label="清除搜索"><X :size="15"/></button></div></div>
     <div class="filters"><select v-model="source" aria-label="筛选来源"><option value="">全部来源</option><option v-for="s in sources" :key="s" :value="s">{{sourceLabels.get(s)||s}}</option></select><select v-model="tag" aria-label="筛选标签"><option value="">全部标签</option><option v-for="t in allTags" :key="t">{{t}}</option></select><label class="hidden-toggle"><input type="checkbox" v-model="showHidden"/>显示隐藏记录</label><span class="filter-note">{{q||tag?'当前显示筛选结果':'未导入的日期不代表没有活动'}}</span></div>
     <div v-if="view==='calendar'" class="calendar-layout">
      <section class="calendar"><div class="weekdays"><span v-for="d in ['一','二','三','四','五','六','日']" :key="d">{{d}}</span></div><div class="calendar-grid"><template v-for="(date,i) in cells" :key="i"><button v-if="date" class="day" :class="{selected:date===selected,today:date===today,hasActivity:byDay.has(date)}" @click="selected=date" :aria-label="`${date}，${byDay.get(date)?.length||0} 条记录`"><div class="day-top"><span class="day-number">{{Number(date.slice(-2))}}</span><span v-if="date===today" class="today-dot"></span></div><template v-if="byDay.has(date)"><span class="day-activity">{{dayCount(date)}} <span>次</span><i v-if="dayCount(date)!=='?'&&byDay.get(date)?.some(a=>a.record.user_message_count===null)" title="包含次数未知的记录">+</i></span><span class="day-title">{{title(byDay.get(date)![0])}}</span><span class="day-dots"><i v-for="n in Math.min(byDay.get(date)!.length,4)" :key="n"></i><small v-if="byDay.get(date)!.length>1">{{byDay.get(date)!.length}} 条主题</small></span></template><span v-else-if="coverage(date).length" class="day-covered">已整理</span></button><div v-else class="day empty-day"></div></template></div><div class="calendar-footer"><span><i class="legend-dot"></i>已有活动记录</span><span>点击日期，查看当天的探索</span></div></section>
      <aside class="day-panel"><div class="day-panel-heading"><div><h2>{{dayLabel}}</h2><p>{{weekday}}<span v-if="selected===today"> · 今天</span></p></div><span class="day-badge">{{dayItems.length}} 条</span></div><div v-if="duration(dayItems)!==null" class="duration-note"><Clock :size="13"/>互动区间合计约 {{duration(dayItems)}} 分钟<span title="按可恢复区间去重合并，不代表本人专注时间">ⓘ</span></div>
       <div v-if="!dayItems.length" class="empty-state compact"><CalendarDays :size="34"/><h3>{{coverage(selected).length?'这天暂无匹配记录':'这一天，还待整理'}}</h3><p>{{q||tag?'试试调整筛选条件。':coverage(selected).length?'已有来源的导入范围覆盖这一天。':'有空时，让 agent 把最近的探索带到这里。'}}</p><button class="text-button" @click="newImport">导入记录<ArrowUpRight :size="14"/></button></div>
       <div v-else class="timeline"><button v-for="a in dayItems" :key="a.id" class="activity-card" :class="{muted:a.annotation.hidden}" @click="openEdit(a)"><div class="card-meta"><span class="source-dot"></span><span>{{a.record.source_label||a.record.source}}</span><EyeOff v-if="a.annotation.hidden" :size="13"/><span class="card-time">{{timeLabel(a.record.first_activity_at,a.record.timezone)}}</span></div><h3>{{title(a)}}</h3><p>{{summary(a)||'暂时没有摘要'}}</p><div class="tags"><span v-for="t in tags(a)" :key="t">{{t}}</span></div><div class="card-footer"><span><MessageCircle :size="12"/>{{countLabel(a.record)}}</span><span v-if="a.record.record_state==='partial'" class="partial">待补全</span><ArrowUpRight :size="14"/></div></button></div>
       <p v-if="coverage(selected).length" class="coverage-note">已有 {{new Set(coverage(selected).map(c=>c.source)).size}} 个来源覆盖此日{{coverage(selected).some(c=>c.status!=='complete')?'，其中部分资料不完整':''}}。</p>
      </aside>
     </div>
     <div v-else class="records-list"><div v-if="!recordList.length" class="empty-state"><Search :size="34"/><h3>暂时没有匹配记录</h3><p>切换月份、调整筛选，或导入最近的活动。</p></div><button v-for="a in recordList" :key="a.id" class="record-row" :class="{muted:a.annotation.hidden}" @click="openEdit(a)"><div class="record-date">{{a.record.activity_date.slice(5).replace('-',' / ')}}<small>{{timeLabel(a.record.first_activity_at,a.record.timezone)}}</small></div><div class="record-main"><h3>{{title(a)}}<EyeOff v-if="a.annotation.hidden" :size="13"/></h3><p>{{summary(a)}}</p><div class="tags"><span v-for="t in tags(a)" :key="t">{{t}}</span></div></div><div class="record-meta"><span>{{a.record.source_label||a.record.source}}</span><small>{{countLabel(a.record)}}</small></div><ChevronRight :size="16"/></button></div>
    </section>
   </template>
   <ArchivePanel v-else-if="view==='archives'"/>
   <section v-else class="imports-page"><div class="section-header"><h2>每一次整理，都有迹可循</h2><a class="secondary" :href="base+'api/v1/export'"><Download :size="15"/>导出日历摘要</a></div><div v-if="!imports.length" class="empty-state"><History :size="38"/><h3>从第一次整理开始</h3><p>使用导入 skill，或上传已经整理好的 JSON 文件。</p><button class="primary" @click="newImport"><Upload :size="16"/>导入记录</button></div><article v-for="batch in imports" :key="batch.id" class="import-card"><div class="import-heading"><span class="import-icon"><Check :size="18"/></span><div><h3>{{dateTime(batch.created_at)}}</h3><p>新增 {{batch.inserted}} · 更新 {{batch.updated}} · 未变化 {{batch.unchanged}}</p></div><span class="success-label">已完成</span></div><div v-if="batch.coverage.length" class="coverage-rows"><div v-for="(c,i) in batch.coverage" :key="i"><strong>{{c.source}}</strong><span>{{c.from}} — {{c.to}}</span><small :class="{partial:c.status!=='complete'}">{{c.status==='complete'?'范围已整理':c.status==='partial'?'部分资料':'完整性未知'}}</small><p v-if="c.note">{{c.note}}</p></div></div><p v-else class="coverage-note">这批记录未声明完整覆盖范围。</p></article></section>
   <footer class="page-footer"><span>AICalendar</span><span>记录来自你的整理 · {{dateTime(lastImport)}}</span></footer>
  </main>
  <div v-if="editing" class="modal-backdrop" @click.self="!busy&&(editing=null)"><section class="modal" role="dialog" aria-modal="true" aria-label="编辑活动记录"><div class="modal-header"><div><span class="eyebrow">{{editing.record.activity_date}} · {{editing.record.source_label||editing.record.source}}</span><h2>一段探索的记录</h2></div><button @click="editing=null" :disabled="busy" aria-label="关闭"><X :size="21"/></button></div><div class="modal-body"><div v-if="error" class="modal-error" role="alert">{{error}}</div><label>主题<input v-model="editTitle" maxlength="160"/></label><label>摘要<textarea v-model="editSummary" rows="5" maxlength="4000"></textarea></label><label>标签<span class="field-hint">用逗号分隔</span><input v-model="editTags"/></label><div class="record-facts"><span>{{countLabel(editing.record)}}</span><span>{{timeLabel(editing.record.first_activity_at,editing.record.timezone)}}<template v-if="editing.record.last_activity_at"> — {{timeLabel(editing.record.last_activity_at,editing.record.timezone)}}</template></span><span>{{editing.record.record_state==='partial'?'记录待补全':'已整理'}}</span></div><button v-if="editing.record.conversation_id" class="secondary" @click="archiveConversation={source:editing.record.source,id:editing.record.conversation_id}"><MessageCircle :size="16"/>查看完整对话</button><label class="check-label"><input type="checkbox" v-model="editHidden"/>隐藏这条记录</label><p class="field-hint">这里的修改会保留，后续导入不会覆盖。</p></div><div class="modal-footer"><button class="text-button" @click="saveEdit(true)" :disabled="busy">恢复来源内容</button><button class="primary" @click="saveEdit()" :disabled="busy||!editTitle.trim()"><Check :size="16"/>{{busy?'保存中…':'保存修改'}}</button></div></section></div>
  <div v-if="archiveConversation" class="modal-backdrop archive-backdrop" @click.self="archiveConversation=null"><section class="modal archive-modal" role="dialog" aria-modal="true" aria-label="完整聊天存档"><div class="modal-header"><h2>完整对话</h2><button @click="archiveConversation=null" aria-label="关闭聊天存档"><X :size="21"/></button></div><div class="modal-body"><ArchivePanel :source="archiveConversation.source" :conversation-id="archiveConversation.id"/></div></section></div>
  <div v-if="importOpen" class="modal-backdrop" @click.self="!busy&&(importOpen=false)"><section class="modal" role="dialog" aria-modal="true" aria-label="导入记录"><div class="modal-header"><div><span class="eyebrow">BRING YOUR JOURNEY HERE</span><h2>把最近的探索带进来</h2></div><button @click="importOpen=false" :disabled="busy" aria-label="关闭"><X :size="21"/></button></div><div class="modal-body"><div v-if="error" class="modal-error" role="alert">{{error}}</div><div class="skill-tip"><Sparkles :size="18"/><div><strong>也可以直接让 agent 整理</strong><p>“用 ai-calendar-import，导入最近一周的 AI 使用记录。”</p></div></div><label class="file-picker"><Upload :size="26"/><strong>{{fileName||'选择整理好的 JSON 文件'}}</strong><span>规范化记录 · 单批最多 500 条 / 1 MiB</span><input type="file" accept=".json,application/json" @change="selectFile"/></label><div v-if="preview" class="preview-result"><h3>{{preview.replay?'这批记录已经导入':'导入预览'}}</h3><div class="preview-counts"><span><strong>{{preview.inserted}}</strong>新增</span><span><strong>{{preview.updated}}</strong>更新</span><span><strong>{{preview.unchanged}}</strong>未变化</span><span :class="{danger:preview.conflicts}"><strong>{{preview.conflicts}}</strong>冲突</span></div><p v-for="(item,i) in preview.items?.filter(x=>x.reason).slice(0,5)" :key="i" class="conflict-line">{{item.source}}：{{item.reason}}</p><p class="field-hint">有冲突时整批不会写入。用户修改过的标题与标签会保留。</p></div></div><div class="modal-footer"><span class="field-hint">先预览，再保存</span><button v-if="!preview" class="primary" :disabled="!importBody||busy" @click="doImport()">{{busy?'检查中…':'预览导入'}}<ArrowUpRight :size="16"/></button><button v-else class="primary" :disabled="busy||preview.conflicts>0||preview.replay" @click="doImport(true)">{{busy?'导入中…':preview.replay?'已导入':'确认导入'}}<Check :size="16"/></button></div></section></div>
 </div>
</template>
